Refactored TransactionViewModel
Spikeysanju/Expenso pull request #215
Opened 2022-01-03 18:45 UTC by yash-k9

Replaced _AndroidViewModel_ in `TransactionViewModel` with _Viewmodel_ , which eliminated the use of viewmodel factory and UiModeDatastore is provided using constructor injection

2022-01-03 20:55 UTC, Spikeysanju approved these changes
PR LGTM 👍

2022-01-03 21:44 UTC, Spikeysanju requested changes
@yash-k9 Can you please Run `./gradlew :spotlessApply` to fix these CI violations. Once it's done I will be merging this PR to master branch. Thanks in advance 🙌

2022-01-04 04:25 UTC, yash-k9 commented
Hi @Spikeysanju, I've made the requested changes. Thank you
![Screenshot 2022-01-04 091223](https://user-images.githubusercontent.com/59912430/148009224-dd2226ac-594a-403b-9286-ac46d4b0363a.png)

2022-01-04 06:14 UTC, Spikeysanju approved these changes
Cool 🙌

2022-01-04 06:23 UTC, merged

2022-01-04 06:37 UTC, Spikeysanju commented
@yash-k9 PR merged. Thanks for your valuable contribution 😃🙌. Have a great day!

2022-01-06 14:37 UTC, yash-k9 commented
Thanks @Spikeysanju :))